### ISSUE TITLE
Migrate to the OP?

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/website#245]
Should we migrate the site sources under `oslc-op/oslc-website`?

**Comment by jamsden** [comment]
Perhaps, let's bring it up at a PGB meeting.

**Comment by berezovskyi** [comment]
Yes, it's on the agenda. But I think TSC can freely make this decision?

--
/Andrew
(from phone)



On Tue, May 21, 2019 at 1:21 PM +0200, "Jim Amsden" <notifications@github.com<mailto:notifications@github.com>> wrote:


Perhaps, let's bring it up at a PGB meeting.

**Comment by berezovskyi** [comment]
@jamsden @axelreichwein I suggest the TSC makes this decision without involving the PGB.

**Comment by berezovskyi** [comment]
I am in favour.

**Comment by jamsden** [comment]
Not sure that's a good idea. Moving something into the oslc-op organization implies the PGB is accepting the responsibility to govern the content. I think we've already made that decision. So from that standpoint, sure the TCS could make that decision. But it wouldn't hurt to bring it up with the PGB, perhaps through an email vote?

**Comment by berezovskyi** [comment]
Not a good idea to migrate or not a good idea for the TSC to decide? I don’t mind PGB input but waiting 14 days for the vote to finish is a bit too much, no?

--
/Andrew
(from phone)



On Thu, Jun 27, 2019 at 9:32 PM +0200, "Jim Amsden" <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure that's a good idea. Moving something into the oslc-op organization implies the PGB is accepting the responsibility to govern the content. I think we've already made that decision. So from that standpoint, sure the TCS could make that decision. But it wouldn't hurt to bring it up with the PGB, perhaps through an email vote?

**Comment by jamsden** [comment]
Not a good idea for the TSC to decide - need PGB input. I would especially like to hear Axel and Bill's views.

 I think the 14 days is only for PSD and PS votes. This is probably to ensure the PGB members have time to review the documents. The PGB should be able to vote on this in a meeting or electronic vote anytime. Most PGB members should be pretty familiar with open-services.net.

**Comment by berezovskyi** [comment]
PGB vote was successful.
