### ISSUE TITLE
Update OSLC Core 3.0 redirect to published PSD04

### ISSUE THREAD

**Issue by jamsden** [oslc-op/website#272]
Update the https://open-services.net/spec/core/latest to point to https://docs.oasis-open-projects.org/oslc-op/core/v3.0/psd04/oslc-core.html

**Comment by berezovskyi** [comment]
Got it

--
/Andrew
(from phone)

On 20 Jan 2020, at 21:13, Jim Amsden <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #272<https://github.com/oslc-op/website/issues/272> to @berezovskyi<https://github.com/berezovskyi>.

**Comment by berezovskyi** [comment]
Updated both https://open-services.net/spec/core/latest and https://open-services.net/spec/core/latest-draft
